/**
 * seedAllClasses.js
 * Seeds 9 exams — Biology, Chemistry, Physics × SS1, SS2, SS3 — 20 MCQ each.
 *
 * Usage:
 *   node scripts/seedAllClasses.js
 *
 * Requirements:
 *   - .env with MONGODB_URL set
 *   - An admin user must already exist in DB
 */

import "dotenv/config";
import mongoose from "mongoose";
import Exam from "../models/Exam.js";
import User from "../models/User.js";

const MONGODB_URL = process.env.MONGODB_URL;
if (!MONGODB_URL) {
  console.error("❌  MONGODB_URL not set in .env");
  process.exit(1);
}

// ═══════════════════════════════════════════════════════════════════════════════
// SS1 BIOLOGY — 20 Questions (Introduction to Biology, Cell Biology, Nutrition)
// ═══════════════════════════════════════════════════════════════════════════════
const ss1Biology = [
  { text: "Biology is the study of:", type:"mcq", marks:1,
    options:[{id:"a",text:"Rocks and minerals"},{id:"b",text:"Living organisms"},{id:"c",text:"Stars and planets"},{id:"d",text:"Chemical reactions"}],
    correctAnswer:"b", explanation:"Biology comes from the Greek 'bios' (life) and 'logos' (study), meaning the science of living things." },
  { text: "Which of these is NOT a characteristic of living things?", type:"mcq", marks:1,
    options:[{id:"a",text:"Growth"},{id:"b",text:"Respiration"},{id:"c",text:"Combustion"},{id:"d",text:"Excretion"}],
    correctAnswer:"c", explanation:"Combustion is a chemical process, not a characteristic of living organisms." },
  { text: "The basic structural and functional unit of life is the:", type:"mcq", marks:1,
    options:[{id:"a",text:"Tissue"},{id:"b",text:"Organ"},{id:"c",text:"Cell"},{id:"d",text:"Molecule"}],
    correctAnswer:"c", explanation:"The cell is the smallest unit capable of carrying out all life processes." },
  { text: "Which organelle controls the activities of the cell?", type:"mcq", marks:1,
    options:[{id:"a",text:"Mitochondria"},{id:"b",text:"Nucleus"},{id:"c",text:"Ribosome"},{id:"d",text:"Vacuole"}],
    correctAnswer:"b", explanation:"The nucleus contains DNA and directs all cellular activities including growth and reproduction." },
  { text: "Chloroplasts are found in:", type:"mcq", marks:1,
    options:[{id:"a",text:"Animal cells only"},{id:"b",text:"Fungal cells only"},{id:"c",text:"Plant cells only"},{id:"d",text:"All cells"}],
    correctAnswer:"c", explanation:"Chloroplasts, which carry out photosynthesis, are found only in plant (and algal) cells." },
  { text: "The process of breaking down food to release energy is called:", type:"mcq", marks:1,
    options:[{id:"a",text:"Photosynthesis"},{id:"b",text:"Digestion"},{id:"c",text:"Respiration"},{id:"d",text:"Transpiration"}],
    correctAnswer:"c", explanation:"Respiration (cellular respiration) breaks down glucose to release ATP energy." },
  { text: "Which nutrient provides the most energy per gram?", type:"mcq", marks:1,
    options:[{id:"a",text:"Carbohydrates"},{id:"b",text:"Proteins"},{id:"c",text:"Vitamins"},{id:"d",text:"Fats"}],
    correctAnswer:"d", explanation:"Fats provide 9 kcal/g compared to 4 kcal/g for carbohydrates and proteins." },
  { text: "Osmosis is the movement of water molecules from a region of:", type:"mcq", marks:1,
    options:[{id:"a",text:"Low concentration to high concentration"},{id:"b",text:"High water potential to low water potential"},{id:"c",text:"High solute to low solute"},{id:"d",text:"Low temperature to high temperature"}],
    correctAnswer:"b", explanation:"Osmosis moves water from high water potential (dilute solution) to low water potential (concentrated solution) through a semi-permeable membrane." },
  { text: "Which blood group is known as the universal donor?", type:"mcq", marks:1,
    options:[{id:"a",text:"A"},{id:"b",text:"B"},{id:"c",text:"AB"},{id:"d",text:"O"}],
    correctAnswer:"d", explanation:"Blood group O negative lacks A, B, and Rh antigens so it can be donated to any blood type." },
  { text: "The backbone of a DNA molecule is made of alternating:", type:"mcq", marks:1,
    options:[{id:"a",text:"Bases and sugars"},{id:"b",text:"Sugars and phosphates"},{id:"c",text:"Bases and phosphates"},{id:"d",text:"Amino acids and sugars"}],
    correctAnswer:"b", explanation:"The DNA backbone consists of alternating deoxyribose sugar and phosphate groups, with nitrogenous bases attached to the sugars." },
  { text: "Which vitamin is essential for blood clotting?", type:"mcq", marks:1,
    options:[{id:"a",text:"Vitamin A"},{id:"b",text:"Vitamin C"},{id:"c",text:"Vitamin D"},{id:"d",text:"Vitamin K"}],
    correctAnswer:"d", explanation:"Vitamin K is required for synthesizing clotting factors, including prothrombin." },
  { text: "Enzymes are biological:", type:"mcq", marks:1,
    options:[{id:"a",text:"Lipids"},{id:"b",text:"Catalysts"},{id:"c",text:"Minerals"},{id:"d",text:"Hormones"}],
    correctAnswer:"b", explanation:"Enzymes are protein catalysts that speed up biochemical reactions without being consumed." },
  { text: "The part of the flower that produces pollen is the:", type:"mcq", marks:1,
    options:[{id:"a",text:"Pistil"},{id:"b",text:"Petal"},{id:"c",text:"Anther"},{id:"d",text:"Sepal"}],
    correctAnswer:"c", explanation:"The anther is the male reproductive part of the flower where pollen grains are produced." },
  { text: "Diffusion is the movement of molecules from a region of:", type:"mcq", marks:1,
    options:[{id:"a",text:"Low concentration to high concentration"},{id:"b",text:"High concentration to low concentration"},{id:"c",text:"Equal concentration to equal concentration"},{id:"d",text:"Cold to warm"}],
    correctAnswer:"b", explanation:"Diffusion moves particles down their concentration gradient, from high to low concentration." },
  { text: "Which organ produces insulin?", type:"mcq", marks:1,
    options:[{id:"a",text:"Liver"},{id:"b",text:"Kidney"},{id:"c",text:"Pancreas"},{id:"d",text:"Stomach"}],
    correctAnswer:"c", explanation:"Insulin is produced by the beta cells of the islets of Langerhans in the pancreas." },
  { text: "Anaerobic respiration in yeast produces:", type:"mcq", marks:1,
    options:[{id:"a",text:"Oxygen and water"},{id:"b",text:"Carbon dioxide and ethanol"},{id:"c",text:"Glucose and oxygen"},{id:"d",text:"Lactic acid and ATP only"}],
    correctAnswer:"b", explanation:"Yeast ferments glucose anaerobically to produce ethanol (alcohol) and carbon dioxide." },
  { text: "The process of cell division that produces gametes is:", type:"mcq", marks:1,
    options:[{id:"a",text:"Mitosis"},{id:"b",text:"Meiosis"},{id:"c",text:"Fission"},{id:"d",text:"Budding"}],
    correctAnswer:"b", explanation:"Meiosis produces haploid gametes (sperm and egg) with half the chromosome number of the parent cell." },
  { text: "Which part of the eye controls the amount of light entering?", type:"mcq", marks:1,
    options:[{id:"a",text:"Cornea"},{id:"b",text:"Retina"},{id:"c",text:"Iris"},{id:"d",text:"Lens"}],
    correctAnswer:"c", explanation:"The iris contains circular and radial muscles that adjust the size of the pupil to control light entry." },
  { text: "Kwashiorkor is caused by deficiency of:", type:"mcq", marks:1,
    options:[{id:"a",text:"Vitamin C"},{id:"b",text:"Carbohydrates"},{id:"c",text:"Protein"},{id:"d",text:"Iron"}],
    correctAnswer:"c", explanation:"Kwashiorkor is a severe form of protein malnutrition common in children after weaning." },
  { text: "The functional unit of the kidney is the:", type:"mcq", marks:1,
    options:[{id:"a",text:"Neuron"},{id:"b",text:"Nephron"},{id:"c",text:"Alveolus"},{id:"d",text:"Villus"}],
    correctAnswer:"b", explanation:"Each kidney contains about one million nephrons that filter blood to form urine." },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SS2 BIOLOGY — 20 Questions (Genetics, Ecology, Physiology, Evolution)
// ═══════════════════════════════════════════════════════════════════════════════
const ss2Biology = [
  { text: "Mendel's Law of Segregation states that:", type:"mcq", marks:1,
    options:[{id:"a",text:"Genes are linked on chromosomes"},{id:"b",text:"Alleles separate during gamete formation"},{id:"c",text:"Dominant alleles always express themselves"},{id:"d",text:"Genes mutate randomly"}],
    correctAnswer:"b", explanation:"During meiosis, paired alleles segregate so each gamete receives only one allele for each trait." },
  { text: "A heterozygous organism has:", type:"mcq", marks:1,
    options:[{id:"a",text:"Two identical alleles"},{id:"b",text:"Two different alleles"},{id:"c",text:"No alleles"},{id:"d",text:"Three alleles"}],
    correctAnswer:"b", explanation:"A heterozygous individual carries two different alleles (e.g. Aa) for a particular gene." },
  { text: "The physical appearance of an organism is its:", type:"mcq", marks:1,
    options:[{id:"a",text:"Genotype"},{id:"b",text:"Phenotype"},{id:"c",text:"Karyotype"},{id:"d",text:"Allele"}],
    correctAnswer:"b", explanation:"Phenotype is the observable characteristics resulting from the interaction of genotype and environment." },
  { text: "Sex in humans is determined by:", type:"mcq", marks:1,
    options:[{id:"a",text:"Autosomes"},{id:"b",text:"The X chromosome from the mother"},{id:"c",text:"The sex chromosome from the father"},{id:"d",text:"Temperature at fertilisation"}],
    correctAnswer:"c", explanation:"Females are XX; males are XY. The father's sperm determines sex by contributing either X (daughter) or Y (son)." },
  { text: "Which of these is a mutualistic relationship?", type:"mcq", marks:1,
    options:[{id:"a",text:"Tapeworm in human intestine"},{id:"b",text:"Rhizobium bacteria in legume root nodules"},{id:"c",text:"Mistletoe on a tree"},{id:"d",text:"Lion eating a zebra"}],
    correctAnswer:"b", explanation:"Rhizobium bacteria fix nitrogen for the plant while benefiting from shelter and carbon — true mutualism." },
  { text: "Which level of organisation contains the most organisms?", type:"mcq", marks:1,
    options:[{id:"a",text:"Population"},{id:"b",text:"Community"},{id:"c",text:"Ecosystem"},{id:"d",text:"Biosphere"}],
    correctAnswer:"d", explanation:"The biosphere is the highest ecological level, encompassing all ecosystems and organisms on Earth." },
  { text: "The primary producers in a food chain are:", type:"mcq", marks:1,
    options:[{id:"a",text:"Herbivores"},{id:"b",text:"Carnivores"},{id:"c",text:"Green plants"},{id:"d",text:"Decomposers"}],
    correctAnswer:"c", explanation:"Green plants (autotrophs) capture solar energy through photosynthesis and form the base of the food chain." },
  { text: "Haemophilia is an example of a:", type:"mcq", marks:1,
    options:[{id:"a",text:"Autosomal dominant disorder"},{id:"b",text:"Autosomal recessive disorder"},{id:"c",text:"Sex-linked recessive disorder"},{id:"d",text:"Chromosomal disorder"}],
    correctAnswer:"c", explanation:"Haemophilia A is caused by a recessive allele on the X chromosome, affecting mostly males." },
  { text: "Evolution is driven primarily by:", type:"mcq", marks:1,
    options:[{id:"a",text:"Natural selection"},{id:"b",text:"Artificial selection only"},{id:"c",text:"Random inheritance"},{id:"d",text:"Intentional adaptation"}],
    correctAnswer:"a", explanation:"Natural selection — differential survival and reproduction of individuals with favourable traits — is the main mechanism of evolution." },
  { text: "Which gas is released during photosynthesis?", type:"mcq", marks:1,
    options:[{id:"a",text:"Carbon dioxide"},{id:"b",text:"Nitrogen"},{id:"c",text:"Oxygen"},{id:"d",text:"Hydrogen"}],
    correctAnswer:"c", explanation:"Oxygen is released as a by-product when water molecules are split during the light-dependent reactions." },
  { text: "The site of gaseous exchange in the lungs is the:", type:"mcq", marks:1,
    options:[{id:"a",text:"Bronchus"},{id:"b",text:"Trachea"},{id:"c",text:"Alveolus"},{id:"d",text:"Pleural cavity"}],
    correctAnswer:"c", explanation:"Alveoli are tiny air sacs with thin moist walls and a rich capillary network ideal for O₂/CO₂ exchange." },
  { text: "Which hormone controls the menstrual cycle's ovulation?", type:"mcq", marks:1,
    options:[{id:"a",text:"Insulin"},{id:"b",text:"Luteinising hormone (LH)"},{id:"c",text:"Adrenaline"},{id:"d",text:"Thyroxine"}],
    correctAnswer:"b", explanation:"The LH surge triggers ovulation around day 14 of the menstrual cycle." },
  { text: "An ecosystem includes:", type:"mcq", marks:1,
    options:[{id:"a",text:"Only the living organisms"},{id:"b",text:"Only the physical environment"},{id:"c",text:"Living organisms and their non-living environment"},{id:"d",text:"Only the food web"}],
    correctAnswer:"c", explanation:"An ecosystem comprises both biotic (living) and abiotic (non-living) components interacting together." },
  { text: "Which part of the brain controls balance and coordination?", type:"mcq", marks:1,
    options:[{id:"a",text:"Cerebrum"},{id:"b",text:"Medulla oblongata"},{id:"c",text:"Cerebellum"},{id:"d",text:"Hypothalamus"}],
    correctAnswer:"c", explanation:"The cerebellum coordinates voluntary movements, balance, and fine motor control." },
  { text: "Transpiration in plants mainly occurs through:", type:"mcq", marks:1,
    options:[{id:"a",text:"Roots"},{id:"b",text:"Stomata"},{id:"c",text:"Lenticels"},{id:"d",text:"Xylem vessels"}],
    correctAnswer:"b", explanation:"About 90% of transpiration occurs through stomata, tiny pores mainly on the underside of leaves." },
  { text: "Which of these is a vector for malaria?", type:"mcq", marks:1,
    options:[{id:"a",text:"Housefly"},{id:"b",text:"Tsetse fly"},{id:"c",text:"Female Anopheles mosquito"},{id:"d",text:"Aedes mosquito"}],
    correctAnswer:"c", explanation:"The female Anopheles mosquito transmits Plasmodium parasites that cause malaria." },
  { text: "Phototropism is the response of plants to:", type:"mcq", marks:1,
    options:[{id:"a",text:"Gravity"},{id:"b",text:"Water"},{id:"c",text:"Light"},{id:"d",text:"Touch"}],
    correctAnswer:"c", explanation:"Phototropism is directional growth in response to light, mediated by the hormone auxin." },
  { text: "The role of decomposers in an ecosystem is to:", type:"mcq", marks:1,
    options:[{id:"a",text:"Produce food by photosynthesis"},{id:"b",text:"Eat primary consumers"},{id:"c",text:"Break down dead organic matter and recycle nutrients"},{id:"d",text:"Fix atmospheric nitrogen"}],
    correctAnswer:"c", explanation:"Decomposers (bacteria and fungi) break down dead organisms, returning nutrients to the soil." },
  { text: "Which molecule carries amino acids to the ribosome during translation?", type:"mcq", marks:1,
    options:[{id:"a",text:"mRNA"},{id:"b",text:"DNA"},{id:"c",text:"tRNA"},{id:"d",text:"rRNA"}],
    correctAnswer:"c", explanation:"Transfer RNA (tRNA) carries specific amino acids to the ribosome, matching anticodons to mRNA codons." },
  { text: "The heartbeat is initiated by the:", type:"mcq", marks:1,
    options:[{id:"a",text:"Atrioventricular node (AVN)"},{id:"b",text:"Sinoatrial node (SAN)"},{id:"c",text:"Purkinje fibres"},{id:"d",text:"Bundle of His"}],
    correctAnswer:"b", explanation:"The SAN (sinoatrial node) in the right atrium is the heart's natural pacemaker, setting the rhythm." },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SS3 BIOLOGY — 20 Questions (Advanced: Ecology, Genetics, Biotechnology, WAEC-level)
// ═══════════════════════════════════════════════════════════════════════════════
const ss3Biology = [
  { text: "Which of the following best describes a gene?", type:"mcq", marks:1,
    options:[{id:"a",text:"A segment of protein"},{id:"b",text:"A segment of DNA that codes for a protein"},{id:"c",text:"The entire DNA of a cell"},{id:"d",text:"A type of RNA molecule"}],
    correctAnswer:"b", explanation:"A gene is a specific sequence of DNA nucleotides that encodes the information for making a functional product, usually a protein." },
  { text: "Sickle cell anaemia results from a mutation that changes:", type:"mcq", marks:1,
    options:[{id:"a",text:"The shape of red blood cell nuclei"},{id:"b",text:"A single amino acid in the haemoglobin beta chain"},{id:"c",text:"The number of chromosomes"},{id:"d",text:"The type of white blood cell produced"}],
    correctAnswer:"b", explanation:"A point mutation replaces glutamic acid with valine at position 6 of the beta-globin chain, causing haemoglobin to polymerize under low O₂." },
  { text: "The Hardy-Weinberg principle applies when:", type:"mcq", marks:1,
    options:[{id:"a",text:"Natural selection is occurring"},{id:"b",text:"A population is large with random mating and no selection or mutation"},{id:"c",text:"Migration is frequent"},{id:"d",text:"The population is small"}],
    correctAnswer:"b", explanation:"Hardy-Weinberg equilibrium requires no selection, no mutation, no migration, random mating, and large population size." },
  { text: "Which enzyme cuts DNA at specific base sequences in genetic engineering?", type:"mcq", marks:1,
    options:[{id:"a",text:"DNA polymerase"},{id:"b",text:"Ligase"},{id:"c",text:"Restriction endonuclease"},{id:"d",text:"Helicase"}],
    correctAnswer:"c", explanation:"Restriction endonucleases (restriction enzymes) recognise specific palindromic sequences and cut double-stranded DNA." },
  { text: "Succession that begins on bare rock is called:", type:"mcq", marks:1,
    options:[{id:"a",text:"Secondary succession"},{id:"b",text:"Primary succession"},{id:"c",text:"Allogenic succession"},{id:"d",text:"Retrogressive succession"}],
    correctAnswer:"b", explanation:"Primary succession starts in a lifeless area (bare rock, new volcanic island) with no prior soil or community." },
  { text: "The nitrogen cycle includes all of these EXCEPT:", type:"mcq", marks:1,
    options:[{id:"a",text:"Nitrification"},{id:"b",text:"Denitrification"},{id:"c",text:"Photosynthesis"},{id:"d",text:"Nitrogen fixation"}],
    correctAnswer:"c", explanation:"Photosynthesis is part of the carbon cycle. The nitrogen cycle involves fixation, nitrification, assimilation, and denitrification." },
  { text: "Which reproductive strategy maximises survival of individual offspring?", type:"mcq", marks:1,
    options:[{id:"a",text:"r-strategy (many small offspring)"},{id:"b",text:"K-strategy (few large offspring with parental care)"},{id:"c",text:"Clonal reproduction"},{id:"d",text:"Parthenogenesis"}],
    correctAnswer:"b", explanation:"K-strategists invest heavily in few offspring, increasing their individual survival probability in stable environments." },
  { text: "PCR (Polymerase Chain Reaction) is used to:", type:"mcq", marks:1,
    options:[{id:"a",text:"Sequence proteins"},{id:"b",text:"Amplify specific DNA sequences"},{id:"c",text:"Cut DNA at restriction sites"},{id:"d",text:"Join DNA fragments"}],
    correctAnswer:"b", explanation:"PCR uses repeated cycles of denaturation, annealing, and extension to exponentially amplify a target DNA region." },
  { text: "An allele that is only expressed in the homozygous state is:", type:"mcq", marks:1,
    options:[{id:"a",text:"Dominant"},{id:"b",text:"Codominant"},{id:"c",text:"Recessive"},{id:"d",text:"Epistatic"}],
    correctAnswer:"c", explanation:"A recessive allele is only phenotypically expressed when two copies are present (homozygous recessive)." },
  { text: "The greenhouse effect is primarily caused by increased levels of:", type:"mcq", marks:1,
    options:[{id:"a",text:"Oxygen"},{id:"b",text:"Nitrogen"},{id:"c",text:"Carbon dioxide and methane"},{id:"d",text:"Argon"}],
    correctAnswer:"c", explanation:"CO₂ and CH₄ trap outgoing infrared radiation, causing global temperatures to rise." },
  { text: "Crossing over during meiosis results in:", type:"mcq", marks:1,
    options:[{id:"a",text:"Identical daughter cells"},{id:"b",text:"Increased genetic variation"},{id:"c",text:"Reduced chromosome number"},{id:"d",text:"DNA replication errors"}],
    correctAnswer:"b", explanation:"Crossing over (recombination) during prophase I shuffles alleles between homologous chromosomes, increasing genetic diversity." },
  { text: "Which hormone triggers the 'fight or flight' response?", type:"mcq", marks:1,
    options:[{id:"a",text:"Insulin"},{id:"b",text:"Glucagon"},{id:"c",text:"Adrenaline"},{id:"d",text:"Cortisol"}],
    correctAnswer:"c", explanation:"Adrenaline (epinephrine) is released by the adrenal medulla, preparing the body for emergency action." },
  { text: "Genetic drift has the greatest effect in:", type:"mcq", marks:1,
    options:[{id:"a",text:"Large, stable populations"},{id:"b",text:"Small, isolated populations"},{id:"c",text:"Populations under strong selection"},{id:"d",text:"Populations with high mutation rates"}],
    correctAnswer:"b", explanation:"In small populations, random chance can significantly change allele frequencies — this is genetic drift." },
  { text: "Which of these is an example of ex-situ conservation?", type:"mcq", marks:1,
    options:[{id:"a",text:"Game reserves"},{id:"b",text:"National parks"},{id:"c",text:"Botanical gardens"},{id:"d",text:"Marine protected areas"}],
    correctAnswer:"c", explanation:"Ex-situ conservation preserves species outside their natural habitat — e.g. botanical gardens, zoos, seed banks." },
  { text: "The primary function of the lymphatic system is:", type:"mcq", marks:1,
    options:[{id:"a",text:"Transport of oxygen"},{id:"b",text:"Return of interstitial fluid to blood and immune defence"},{id:"c",text:"Digestion of fats"},{id:"d",text:"Filtration of blood"}],
    correctAnswer:"b", explanation:"The lymphatic system drains tissue fluid back into circulation and plays a central role in immune responses." },
  { text: "Which base pairs with Adenine in RNA?", type:"mcq", marks:1,
    options:[{id:"a",text:"Thymine"},{id:"b",text:"Guanine"},{id:"c",text:"Cytosine"},{id:"d",text:"Uracil"}],
    correctAnswer:"d", explanation:"RNA contains uracil instead of thymine. During transcription, Adenine on DNA pairs with Uracil in mRNA." },
  { text: "Biological magnification (biomagnification) means:", type:"mcq", marks:1,
    options:[{id:"a",text:"Organisms getting larger up the food chain"},{id:"b",text:"Toxins increasing in concentration at higher trophic levels"},{id:"c",text:"Energy increasing up the food chain"},{id:"d",text:"Nutrients accumulating in soils"}],
    correctAnswer:"b", explanation:"Persistent toxins (e.g. DDT, mercury) become more concentrated in organisms at higher trophic levels as they pass through the food chain." },
  { text: "Apoptosis is:", type:"mcq", marks:1,
    options:[{id:"a",text:"Uncontrolled cell division"},{id:"b",text:"Programmed cell death"},{id:"c",text:"Cell fusion"},{id:"d",text:"DNA replication"}],
    correctAnswer:"b", explanation:"Apoptosis is a regulated process of cell self-destruction essential for development, immune function, and cancer prevention." },
  { text: "Which of these is the correct order of taxonomic classification from broadest to most specific?", type:"mcq", marks:1,
    options:[{id:"a",text:"Kingdom, Phylum, Class, Order, Family, Genus, Species"},{id:"b",text:"Species, Genus, Family, Order, Class, Phylum, Kingdom"},{id:"c",text:"Kingdom, Class, Phylum, Order, Family, Genus, Species"},{id:"d",text:"Phylum, Kingdom, Class, Family, Order, Genus, Species"}],
    correctAnswer:"a", explanation:"The hierarchy from broadest to most specific is: Domain, Kingdom, Phylum, Class, Order, Family, Genus, Species." },
  { text: "Active transport differs from diffusion because it:", type:"mcq", marks:1,
    options:[{id:"a",text:"Moves molecules down a concentration gradient"},{id:"b",text:"Does not require a membrane"},{id:"c",text:"Requires energy (ATP) and moves molecules against the gradient"},{id:"d",text:"Only moves water molecules"}],
    correctAnswer:"c", explanation:"Active transport uses carrier proteins and ATP to move substances against their concentration gradient." },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SS1 CHEMISTRY — 20 Questions (Intro, Atomic Structure, States of Matter, Bonding)
// ═══════════════════════════════════════════════════════════════════════════════
const ss1Chemistry = [
  { text: "The smallest particle of an element that can take part in a chemical reaction is:", type:"mcq", marks:1,
    options:[{id:"a",text:"Molecule"},{id:"b",text:"Atom"},{id:"c",text:"Ion"},{id:"d",text:"Proton"}],
    correctAnswer:"b", explanation:"An atom is the smallest unit of an element that retains the chemical properties of that element." },
  { text: "The atomic number of an element is equal to the number of:", type:"mcq", marks:1,
    options:[{id:"a",text:"Neutrons"},{id:"b",text:"Protons"},{id:"c",text:"Nucleons"},{id:"d",text:"Electrons in the nucleus"}],
    correctAnswer:"b", explanation:"The atomic number equals the number of protons in the nucleus, which also equals the number of electrons in a neutral atom." },
  { text: "Which state of matter has a definite volume but no definite shape?", type:"mcq", marks:1,
    options:[{id:"a",text:"Solid"},{id:"b",text:"Gas"},{id:"c",text:"Liquid"},{id:"d",text:"Plasma"}],
    correctAnswer:"c", explanation:"Liquids have a fixed volume but take the shape of their container because their particles can flow past each other." },
  { text: "A compound is a substance made of:", type:"mcq", marks:1,
    options:[{id:"a",text:"One type of atom only"},{id:"b",text:"Two or more elements chemically combined"},{id:"c",text:"Two or more elements physically mixed"},{id:"d",text:"Atoms of the same element in different forms"}],
    correctAnswer:"b", explanation:"A compound contains two or more elements joined by chemical bonds in fixed proportions, with properties different from its constituent elements." },
  { text: "The process by which a solid changes directly to a gas is called:", type:"mcq", marks:1,
    options:[{id:"a",text:"Evaporation"},{id:"b",text:"Condensation"},{id:"c",text:"Sublimation"},{id:"d",text:"Melting"}],
    correctAnswer:"c", explanation:"Sublimation is the direct transition from solid to gas (e.g. dry ice → CO₂ gas, iodine crystals)." },
  { text: "Which subatomic particle has no charge?", type:"mcq", marks:1,
    options:[{id:"a",text:"Proton"},{id:"b",text:"Electron"},{id:"c",text:"Neutron"},{id:"d",text:"Ion"}],
    correctAnswer:"c", explanation:"Neutrons are electrically neutral particles found in the atomic nucleus alongside protons." },
  { text: "An ionic bond is formed by:", type:"mcq", marks:1,
    options:[{id:"a",text:"Sharing of electrons"},{id:"b",text:"Transfer of electrons from one atom to another"},{id:"c",text:"Sharing of protons"},{id:"d",text:"Electrostatic repulsion"}],
    correctAnswer:"b", explanation:"Ionic bonds form when one atom donates electrons to another, creating oppositely charged ions that attract each other." },
  { text: "The pH of a neutral solution at 25°C is:", type:"mcq", marks:1,
    options:[{id:"a",text:"0"},{id:"b",text:"7"},{id:"c",text:"14"},{id:"d",text:"1"}],
    correctAnswer:"b", explanation:"A neutral solution has equal concentrations of H⁺ and OH⁻ ions, corresponding to pH 7 at 25°C." },
  { text: "Which gas is produced when a metal reacts with dilute acid?", type:"mcq", marks:1,
    options:[{id:"a",text:"Oxygen"},{id:"b",text:"Carbon dioxide"},{id:"c",text:"Hydrogen"},{id:"d",text:"Nitrogen"}],
    correctAnswer:"c", explanation:"Metals react with dilute acids to form a salt and hydrogen gas: e.g. Zn + H₂SO₄ → ZnSO₄ + H₂." },
  { text: "The valency of carbon is:", type:"mcq", marks:1,
    options:[{id:"a",text:"2"},{id:"b",text:"4"},{id:"c",text:"1"},{id:"d",text:"3"}],
    correctAnswer:"b", explanation:"Carbon has 4 electrons in its outer shell and forms 4 covalent bonds, giving it a valency of 4." },
  { text: "Isotopes are atoms of the same element with different numbers of:", type:"mcq", marks:1,
    options:[{id:"a",text:"Protons"},{id:"b",text:"Electrons"},{id:"c",text:"Neutrons"},{id:"d",text:"Protons and electrons"}],
    correctAnswer:"c", explanation:"Isotopes have the same atomic number (protons) but different mass numbers due to different numbers of neutrons." },
  { text: "Which of these is a physical change?", type:"mcq", marks:1,
    options:[{id:"a",text:"Burning wood"},{id:"b",text:"Rusting iron"},{id:"c",text:"Dissolving sugar in water"},{id:"d",text:"Cooking an egg"}],
    correctAnswer:"c", explanation:"Dissolving sugar is a physical change — no new substance is formed and it can be reversed by evaporation." },
  { text: "The law of conservation of mass states that:", type:"mcq", marks:1,
    options:[{id:"a",text:"Mass is created during reactions"},{id:"b",text:"Mass is destroyed during reactions"},{id:"c",text:"Total mass of reactants equals total mass of products"},{id:"d",text:"Energy and mass are interchangeable"}],
    correctAnswer:"c", explanation:"In a chemical reaction, matter is neither created nor destroyed; the total mass of reactants equals that of products." },
  { text: "Which element is liquid at room temperature?", type:"mcq", marks:1,
    options:[{id:"a",text:"Sodium"},{id:"b",text:"Mercury"},{id:"c",text:"Sulphur"},{id:"d",text:"Phosphorus"}],
    correctAnswer:"b", explanation:"Mercury (Hg) is the only metal that exists as a liquid at standard room temperature (25°C)." },
  { text: "A covalent bond involves:", type:"mcq", marks:1,
    options:[{id:"a",text:"Transfer of electrons"},{id:"b",text:"Sharing of electrons"},{id:"c",text:"Transfer of protons"},{id:"d",text:"Electrostatic attraction between ions"}],
    correctAnswer:"b", explanation:"Covalent bonds form when two atoms share one or more pairs of electrons to achieve stable electron configurations." },
  { text: "The relative molecular mass of water (H₂O) is:", type:"mcq", marks:1,
    options:[{id:"a",text:"10"},{id:"b",text:"16"},{id:"c",text:"18"},{id:"d",text:"20"}],
    correctAnswer:"c", explanation:"H₂O: (2 × 1) + (1 × 16) = 2 + 16 = 18 g/mol." },
  { text: "Which of these is NOT a noble gas?", type:"mcq", marks:1,
    options:[{id:"a",text:"Neon"},{id:"b",text:"Argon"},{id:"c",text:"Nitrogen"},{id:"d",text:"Helium"}],
    correctAnswer:"c", explanation:"Nitrogen (N₂) is a diatomic non-metal gas in Group 15, not a noble gas. Noble gases are in Group 18." },
  { text: "During electrolysis, oxidation occurs at the:", type:"mcq", marks:1,
    options:[{id:"a",text:"Cathode"},{id:"b",text:"Anode"},{id:"c",text:"Electrolyte"},{id:"d",text:"Battery"}],
    correctAnswer:"b", explanation:"Oxidation (loss of electrons) occurs at the anode. Remember: AN OX (Anode = Oxidation), RED CAT (Cathode = Reduction)." },
  { text: "Alloys are:", type:"mcq", marks:1,
    options:[{id:"a",text:"Pure metals"},{id:"b",text:"Non-metallic compounds"},{id:"c",text:"Mixtures of a metal with other elements"},{id:"d",text:"Ionic compounds of metals"}],
    correctAnswer:"c", explanation:"An alloy is a mixture of a metal with one or more other elements (metals or non-metals) to improve properties." },
  { text: "The chemical formula of common salt is:", type:"mcq", marks:1,
    options:[{id:"a",text:"KCl"},{id:"b",text:"NaOH"},{id:"c",text:"NaCl"},{id:"d",text:"CaCl₂"}],
    correctAnswer:"c", explanation:"Common salt (table salt) is sodium chloride, NaCl, formed from sodium and chloride ions." },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SS2 CHEMISTRY — 20 Questions (Stoichiometry, Acids/Bases, Kinetics, Organic Intro)
// ═══════════════════════════════════════════════════════════════════════════════
const ss2Chemistry = [
  { text: "One mole of any substance contains approximately:", type:"mcq", marks:1,
    options:[{id:"a",text:"6.02 × 10²³ particles"},{id:"b",text:"3.01 × 10²³ particles"},{id:"c",text:"6.02 × 10²⁰ particles"},{id:"d",text:"1.67 × 10⁻²⁴ particles"}],
    correctAnswer:"a", explanation:"Avogadro's number (6.02 × 10²³) is the number of entities (atoms, molecules, ions) in one mole of substance." },
  { text: "A strong acid is one that:", type:"mcq", marks:1,
    options:[{id:"a",text:"Is concentrated"},{id:"b",text:"Fully dissociates in water"},{id:"c",text:"Has a high pH"},{id:"d",text:"Is corrosive"}],
    correctAnswer:"b", explanation:"A strong acid (e.g. HCl, H₂SO₄, HNO₃) completely dissociates into ions in aqueous solution." },
  { text: "The rate of a chemical reaction can be increased by:", type:"mcq", marks:1,
    options:[{id:"a",text:"Decreasing temperature"},{id:"b",text:"Decreasing concentration"},{id:"c",text:"Adding a catalyst"},{id:"d",text:"Increasing particle size"}],
    correctAnswer:"c", explanation:"A catalyst provides an alternative reaction pathway with lower activation energy, increasing reaction rate without being consumed." },
  { text: "Which of the following is a homologous series?", type:"mcq", marks:1,
    options:[{id:"a",text:"CH₄, C₂H₄, C₃H₆"},{id:"b",text:"CH₄, C₂H₆, C₃H₈"},{id:"c",text:"C₂H₂, C₃H₄, C₅H₈"},{id:"d",text:"CH₄, C₂H₂, C₃H₆"}],
    correctAnswer:"b", explanation:"Alkanes (CH₄, C₂H₆, C₃H₈) form a homologous series differing by –CH₂– with the general formula CₙH₂ₙ₊₂." },
  { text: "In a neutralisation reaction, acid + base produces:", type:"mcq", marks:1,
    options:[{id:"a",text:"Acid + water"},{id:"b",text:"Salt + water"},{id:"c",text:"Base + gas"},{id:"d",text:"Salt + gas"}],
    correctAnswer:"b", explanation:"Neutralisation: acid + base → salt + water. E.g. HCl + NaOH → NaCl + H₂O." },
  { text: "The empirical formula shows:", type:"mcq", marks:1,
    options:[{id:"a",text:"The actual number of each atom in a molecule"},{id:"b",text:"The simplest whole number ratio of atoms"},{id:"c",text:"The 3D arrangement of atoms"},{id:"d",text:"The molecular mass of a compound"}],
    correctAnswer:"b", explanation:"The empirical formula gives the simplest integer ratio of atoms (e.g. glucose C₆H₁₂O₆ has empirical formula CH₂O)." },
  { text: "Which indicator turns red in acidic solutions?", type:"mcq", marks:1,
    options:[{id:"a",text:"Phenolphthalein"},{id:"b",text:"Universal indicator"},{id:"c",text:"Litmus"},{id:"d",text:"Methyl orange"}],
    correctAnswer:"c", explanation:"Litmus turns red in acid and blue in base. Methyl orange turns red in strong acids and yellow in alkali." },
  { text: "Fractional distillation separates mixtures based on differences in:", type:"mcq", marks:1,
    options:[{id:"a",text:"Density"},{id:"b",text:"Boiling point"},{id:"c",text:"Solubility"},{id:"d",text:"Colour"}],
    correctAnswer:"b", explanation:"Fractional distillation exploits different boiling points to separate liquid mixtures, e.g. crude oil refining." },
  { text: "The functional group of alcohols is:", type:"mcq", marks:1,
    options:[{id:"a",text:"–COOH"},{id:"b",text:"–CHO"},{id:"c",text:"–OH"},{id:"d",text:"–NH₂"}],
    correctAnswer:"c", explanation:"Alcohols contain the hydroxyl (–OH) functional group. E.g. ethanol is CH₃CH₂OH." },
  { text: "Which gas turns lime water milky?", type:"mcq", marks:1,
    options:[{id:"a",text:"Hydrogen"},{id:"b",text:"Oxygen"},{id:"c",text:"Carbon dioxide"},{id:"d",text:"Sulphur dioxide"}],
    correctAnswer:"c", explanation:"CO₂ reacts with calcium hydroxide (lime water): CO₂ + Ca(OH)₂ → CaCO₃ (white precipitate) + H₂O." },
  { text: "The molar volume of an ideal gas at STP is:", type:"mcq", marks:1,
    options:[{id:"a",text:"11.2 dm³"},{id:"b",text:"22.4 dm³"},{id:"c",text:"44.8 dm³"},{id:"d",text:"24.0 dm³"}],
    correctAnswer:"b", explanation:"At STP (0°C, 1 atm), one mole of any ideal gas occupies 22.4 dm³ (litres)." },
  { text: "Cracking of petroleum produces:", type:"mcq", marks:1,
    options:[{id:"a",text:"Only alkanes"},{id:"b",text:"Alkanes and alkenes"},{id:"c",text:"Only alkenes"},{id:"d",text:"Alkynes only"}],
    correctAnswer:"b", explanation:"Thermal or catalytic cracking of long-chain hydrocarbons produces shorter alkanes and alkenes (used in polymers and fuels)." },
  { text: "In the periodic table, elements in the same group have the same:", type:"mcq", marks:1,
    options:[{id:"a",text:"Mass number"},{id:"b",text:"Number of electron shells"},{id:"c",text:"Number of outer shell electrons"},{id:"d",text:"Atomic mass"}],
    correctAnswer:"c", explanation:"Elements in the same group have the same number of valence electrons, giving them similar chemical properties." },
  { text: "Which of these is an addition polymer?", type:"mcq", marks:1,
    options:[{id:"a",text:"Nylon"},{id:"b",text:"Polyester"},{id:"c",text:"Polythene (polyethylene)"},{id:"d",text:"Bakelite"}],
    correctAnswer:"c", explanation:"Polythene is made by addition polymerisation of ethene monomers (CH₂=CH₂) n → (–CH₂–CH₂–) n." },
  { text: "The oxidation number of oxygen in most compounds is:", type:"mcq", marks:1,
    options:[{id:"a",text:"+2"},{id:"b",text:"+1"},{id:"c",text:"-2"},{id:"d",text:"0"}],
    correctAnswer:"c", explanation:"Oxygen typically has an oxidation number of −2 in compounds (exception: peroxides −1, OF₂ +2)." },
  { text: "Which test confirms the presence of a reducing sugar?", type:"mcq", marks:1,
    options:[{id:"a",text:"Iodine test"},{id:"b",text:"Biuret test"},{id:"c",text:"Benedict's test"},{id:"d",text:"Emulsion test"}],
    correctAnswer:"c", explanation:"Benedict's reagent turns from blue to a brick-red precipitate (Cu₂O) when heated with a reducing sugar." },
  { text: "Electrolysis of brine (NaCl solution) produces:", type:"mcq", marks:1,
    options:[{id:"a",text:"Sodium and oxygen"},{id:"b",text:"Chlorine, hydrogen and sodium hydroxide"},{id:"c",text:"Sodium and chlorine only"},{id:"d",text:"Hydrogen and oxygen"}],
    correctAnswer:"b", explanation:"Electrolysis of brine yields Cl₂ at the anode, H₂ at the cathode, and NaOH in solution — industrially important products." },
  { text: "The IUPAC name for CH₃CH₂OH is:", type:"mcq", marks:1,
    options:[{id:"a",text:"Methanol"},{id:"b",text:"Ethanol"},{id:"c",text:"Propanol"},{id:"d",text:"Butanol"}],
    correctAnswer:"b", explanation:"CH₃CH₂OH has 2 carbon atoms with a hydroxyl group → ethanol (ethan-1-ol)." },
  { text: "A buffer solution resists changes in:", type:"mcq", marks:1,
    options:[{id:"a",text:"Temperature"},{id:"b",text:"Pressure"},{id:"c",text:"pH"},{id:"d",text:"Concentration"}],
    correctAnswer:"c", explanation:"A buffer solution (weak acid + its conjugate base, or vice versa) maintains a relatively constant pH when small amounts of acid or base are added." },
  { text: "The Haber process is used to manufacture:", type:"mcq", marks:1,
    options:[{id:"a",text:"Sulphuric acid"},{id:"b",text:"Ammonia"},{id:"c",text:"Nitric acid"},{id:"d",text:"Sodium hydroxide"}],
    correctAnswer:"b", explanation:"The Haber process combines N₂ and H₂ over an iron catalyst at 450°C and 200 atm to produce ammonia: N₂ + 3H₂ ⇌ 2NH₃." },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SS3 CHEMISTRY — 20 Questions (Advanced Organic, Electrochemistry, Equilibrium, WAEC)
// ═══════════════════════════════════════════════════════════════════════════════
const ss3Chemistry = [
  { text: "Le Chatelier's principle states that if a system at equilibrium is disturbed, it will:", type:"mcq", marks:1,
    options:[{id:"a",text:"Stop reacting"},{id:"b",text:"Shift to oppose the change and re-establish equilibrium"},{id:"c",text:"Always increase the rate of the forward reaction"},{id:"d",text:"Shift to increase temperature"}],
    correctAnswer:"b", explanation:"Le Chatelier's principle: a system at equilibrium responds to a disturbance (concentration, temperature, pressure) by shifting to minimise that disturbance." },
  { text: "The standard electrode potential of the standard hydrogen electrode is:", type:"mcq", marks:1,
    options:[{id:"a",text:"+1.00 V"},{id:"b",text:"-1.00 V"},{id:"c",text:"0.00 V"},{id:"d",text:"+0.76 V"}],
    correctAnswer:"c", explanation:"The SHE (H⁺/H₂, 1M, 1 atm, 25°C) is assigned 0.00 V by international convention and used as the reference electrode." },
  { text: "Which type of isomerism is shown by compounds with the same molecular formula but different functional groups?", type:"mcq", marks:1,
    options:[{id:"a",text:"Chain isomerism"},{id:"b",text:"Positional isomerism"},{id:"c",text:"Functional group isomerism"},{id:"d",text:"Geometric isomerism"}],
    correctAnswer:"c", explanation:"Functional group isomers have the same molecular formula but different functional groups, e.g. ethanol (C₂H₅OH) and dimethyl ether (CH₃OCH₃)." },
  { text: "In the Contact process, SO₂ is oxidised to SO₃ using:", type:"mcq", marks:1,
    options:[{id:"a",text:"Platinum catalyst"},{id:"b",text:"Iron catalyst"},{id:"c",text:"Vanadium(V) oxide catalyst"},{id:"d",text:"Nickel catalyst"}],
    correctAnswer:"c", explanation:"The Contact process uses V₂O₅ (vanadium pentoxide) as catalyst at ~450°C to convert SO₂ to SO₃ for sulphuric acid production." },
  { text: "Saponification is:", type:"mcq", marks:1,
    options:[{id:"a",text:"Fermentation of ethanol"},{id:"b",text:"Hydrolysis of an ester with alkali to produce soap"},{id:"c",text:"Oxidation of an alcohol"},{id:"d",text:"Addition of HBr to alkenes"}],
    correctAnswer:"b", explanation:"Saponification is the alkaline hydrolysis of a fat or oil (ester) to produce glycerol and soap (fatty acid salts)." },
  { text: "The Kc expression for the reaction N₂ + 3H₂ ⇌ 2NH₃ is:", type:"mcq", marks:1,
    options:[
      {id:"a",text:"Kc = [NH₃]² / ([N₂][H₂]³)"},
      {id:"b",text:"Kc = [N₂][H₂]³ / [NH₃]²"},
      {id:"c",text:"Kc = [NH₃] / ([N₂][H₂])"},
      {id:"d",text:"Kc = [NH₃]² × [N₂][H₂]³"}
    ],
    correctAnswer:"a", explanation:"Kc = [products]^stoich / [reactants]^stoich. Products [NH₃]² in numerator; reactants [N₂]¹[H₂]³ in denominator." },
  { text: "Markovnikov's rule predicts that in addition to HX across an alkene, H adds to the carbon:", type:"mcq", marks:1,
    options:[{id:"a",text:"With fewer hydrogen atoms"},{id:"b",text:"With more hydrogen atoms"},{id:"c",text:"That is more substituted"},{id:"d",text:"That bears the halogen"}],
    correctAnswer:"b", explanation:"Markovnikov's rule: H attaches to the carbon that already has more H atoms (the less substituted carbon), forming the more stable carbocation intermediate." },
  { text: "Which compound gives a silver mirror with Tollens' reagent?", type:"mcq", marks:1,
    options:[{id:"a",text:"Ethanoic acid"},{id:"b",text:"Propanone"},{id:"c",text:"Ethanal (acetaldehyde)"},{id:"d",text:"Ethanol"}],
    correctAnswer:"c", explanation:"Tollens' reagent (ammoniacal AgNO₃) is reduced to silver by aldehydes. Ketones and carboxylic acids do not react." },
  { text: "The pH of a 0.01 mol/dm³ HCl solution is:", type:"mcq", marks:1,
    options:[{id:"a",text:"1"},{id:"b",text:"2"},{id:"c",text:"3"},{id:"d",text:"12"}],
    correctAnswer:"b", explanation:"HCl is a strong acid, fully dissociated: [H⁺] = 0.01 = 10⁻² mol/dm³. pH = –log(10⁻²) = 2." },
  { text: "Electrolysis of copper(II) sulphate with copper electrodes results in:", type:"mcq", marks:1,
    options:[{id:"a",text:"Copper deposited at anode"},{id:"b",text:"Copper deposited at cathode and anode dissolves"},{id:"c",text:"Oxygen released at cathode"},{id:"d",text:"No change"}],
    correctAnswer:"b", explanation:"Cu²⁺ ions are reduced at cathode (Cu deposited); the copper anode oxidises and dissolves, replenishing Cu²⁺. Net effect: copper transferred from anode to cathode." },
  { text: "Which of these is a condensation polymer?", type:"mcq", marks:1,
    options:[{id:"a",text:"Polypropene"},{id:"b",text:"Polystyrene"},{id:"c",text:"Nylon-6,6"},{id:"d",text:"Polyvinylchloride (PVC)"}],
    correctAnswer:"c", explanation:"Nylon-6,6 is made by condensation polymerisation of hexanedioic acid and 1,6-diaminohexane, releasing water as a by-product." },
  { text: "The first ionisation energy generally increases across a period because:", type:"mcq", marks:1,
    options:[{id:"a",text:"Atomic radius increases"},{id:"b",text:"Nuclear charge increases with same shielding"},{id:"c",text:"Electrons are added to inner shells"},{id:"d",text:"Atomic mass decreases"}],
    correctAnswer:"b", explanation:"Across a period, proton number increases while shielding stays approximately constant, pulling electrons closer and requiring more energy to remove." },
  { text: "A galvanic cell converts:", type:"mcq", marks:1,
    options:[{id:"a",text:"Electrical energy to chemical energy"},{id:"b",text:"Chemical energy to electrical energy"},{id:"c",text:"Heat energy to electrical energy"},{id:"d",text:"Light energy to chemical energy"}],
    correctAnswer:"b", explanation:"A galvanic (voltaic) cell uses spontaneous redox reactions to generate electrical energy, e.g. the Daniell cell." },
  { text: "What is the degree of unsaturation (DoU) of benzene (C₆H₆)?", type:"mcq", marks:1,
    options:[{id:"a",text:"2"},{id:"b",text:"3"},{id:"c",text:"4"},{id:"d",text:"6"}],
    correctAnswer:"c", explanation:"DoU = (2C + 2 + N – H – X) / 2 = (12 + 2 – 6) / 2 = 8/2 = 4. Benzene has 3 double bonds + 1 ring = 4." },
  { text: "Esterification is the reaction between:", type:"mcq", marks:1,
    options:[{id:"a",text:"Two alcohols"},{id:"b",text:"An alcohol and a carboxylic acid"},{id:"c",text:"An acid and a base"},{id:"d",text:"An aldehyde and a ketone"}],
    correctAnswer:"b", explanation:"Esterification: alcohol + carboxylic acid ⇌ ester + water (reversible, acid catalyst). E.g. CH₃OH + CH₃COOH ⇌ CH₃COOCH₃ + H₂O." },
  { text: "Radioactive decay that involves emission of a helium nucleus is:", type:"mcq", marks:1,
    options:[{id:"a",text:"Beta decay"},{id:"b",text:"Gamma decay"},{id:"c",text:"Alpha decay"},{id:"d",text:"Positron emission"}],
    correctAnswer:"c", explanation:"Alpha particles are helium-4 nuclei (²He₄), emitted from the nucleus of heavy radioactive isotopes." },
  { text: "The Ostwald process is used to manufacture:", type:"mcq", marks:1,
    options:[{id:"a",text:"Ammonia"},{id:"b",text:"Nitric acid"},{id:"c",text:"Sulphuric acid"},{id:"d",text:"Hydrochloric acid"}],
    correctAnswer:"b", explanation:"The Ostwald process oxidises ammonia over platinum catalyst to eventually produce nitric acid: NH₃ → NO → NO₂ → HNO₃." },
  { text: "Which reagent is used to distinguish between alkanes and alkenes?", type:"mcq", marks:1,
    options:[{id:"a",text:"Lime water"},{id:"b",text:"Dilute H₂SO₄"},{id:"c",text:"Bromine water"},{id:"d",text:"Universal indicator"}],
    correctAnswer:"c", explanation:"Bromine water (orange-brown) is decolourised by alkenes through electrophilic addition across the C=C, but alkanes do not react." },
  { text: "Stainless steel is an alloy of iron and:", type:"mcq", marks:1,
    options:[{id:"a",text:"Copper and tin"},{id:"b",text:"Chromium and nickel"},{id:"c",text:"Zinc and lead"},{id:"d",text:"Aluminium and silicon"}],
    correctAnswer:"b", explanation:"Stainless steel typically contains 10–18% chromium (and often nickel), which forms a passive oxide layer preventing corrosion." },
  { text: "In an SN2 reaction, the nucleophile attacks from:", type:"mcq", marks:1,
    options:[{id:"a",text:"The same side as the leaving group"},{id:"b",text:"The opposite side to the leaving group (backside attack)"},{id:"c",text:"The top of the molecule"},{id:"d",text:"Any direction with equal probability"}],
    correctAnswer:"b", explanation:"SN2 involves concerted backside attack by the nucleophile as the leaving group departs, resulting in inversion of configuration (Walden inversion)." },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SS1 PHYSICS — 20 Questions (Measurements, Motion, Forces, Energy)
// ═══════════════════════════════════════════════════════════════════════════════
const ss1Physics = [
  { text: "The SI unit of force is the:", type:"mcq", marks:1,
    options:[{id:"a",text:"Joule"},{id:"b",text:"Watt"},{id:"c",text:"Newton"},{id:"d",text:"Pascal"}],
    correctAnswer:"c", explanation:"The Newton (N) is the SI unit of force. 1 N = 1 kg·m/s², the force needed to accelerate 1 kg by 1 m/s²." },
  { text: "Speed is defined as:", type:"mcq", marks:1,
    options:[{id:"a",text:"Distance divided by time"},{id:"b",text:"Displacement divided by time"},{id:"c",text:"Force divided by mass"},{id:"d",text:"Mass multiplied by velocity"}],
    correctAnswer:"a", explanation:"Speed = distance / time. It is a scalar quantity (no direction), unlike velocity which is a vector." },
  { text: "Which of the following is a vector quantity?", type:"mcq", marks:1,
    options:[{id:"a",text:"Speed"},{id:"b",text:"Mass"},{id:"c",text:"Temperature"},{id:"d",text:"Velocity"}],
    correctAnswer:"d", explanation:"Velocity has both magnitude and direction (a vector). Speed, mass, and temperature are scalars." },
  { text: "Newton's First Law of Motion states that an object will remain at rest or in uniform motion unless:", type:"mcq", marks:1,
    options:[{id:"a",text:"It has mass"},{id:"b",text:"An unbalanced force acts on it"},{id:"c",text:"Its velocity changes"},{id:"d",text:"Gravity acts on it"}],
    correctAnswer:"b", explanation:"The First Law (Law of Inertia): objects maintain their state of motion unless acted upon by a net (unbalanced) external force." },
  { text: "The acceleration due to gravity on Earth is approximately:", type:"mcq", marks:1,
    options:[{id:"a",text:"9.8 m/s"},{id:"b",text:"9.8 m/s²"},{id:"c",text:"10 N/kg only"},{id:"d",text:"8.9 m/s²"}],
    correctAnswer:"b", explanation:"g ≈ 9.8 m/s² (often rounded to 10 m/s² in calculations). It represents both the gravitational field strength and free-fall acceleration." },
  { text: "Work is done when:", type:"mcq", marks:1,
    options:[{id:"a",text:"A force is applied with no movement"},{id:"b",text:"A force causes displacement in its direction"},{id:"c",text:"An object has kinetic energy"},{id:"d",text:"Heat is produced"}],
    correctAnswer:"b", explanation:"Work = Force × displacement in the direction of force. No displacement means no work done, regardless of force applied." },
  { text: "The principle of conservation of energy states:", type:"mcq", marks:1,
    options:[{id:"a",text:"Energy can be created from nothing"},{id:"b",text:"Energy can be destroyed but not created"},{id:"c",text:"Energy cannot be created or destroyed, only transformed"},{id:"d",text:"Total energy always increases"}],
    correctAnswer:"c", explanation:"Energy is conserved — it changes from one form to another (e.g. kinetic to potential) but the total in an isolated system is constant." },
  { text: "The unit of power is the:", type:"mcq", marks:1,
    options:[{id:"a",text:"Newton"},{id:"b",text:"Joule"},{id:"c",text:"Watt"},{id:"d",text:"Pascal"}],
    correctAnswer:"c", explanation:"Power = Energy/time. 1 Watt = 1 Joule per second (1 W = 1 J/s)." },
  { text: "Pressure is defined as:", type:"mcq", marks:1,
    options:[{id:"a",text:"Force times area"},{id:"b",text:"Force divided by area"},{id:"c",text:"Mass divided by volume"},{id:"d",text:"Weight times height"}],
    correctAnswer:"b", explanation:"Pressure = Force / Area. SI unit is the Pascal (Pa) where 1 Pa = 1 N/m²." },
  { text: "Which of the following best describes inertia?", type:"mcq", marks:1,
    options:[{id:"a",text:"The tendency of an object to resist changes in its motion"},{id:"b",text:"The force of gravity on an object"},{id:"c",text:"The energy stored in a moving object"},{id:"d",text:"The rate of change of momentum"}],
    correctAnswer:"a", explanation:"Inertia is the property of matter that resists changes in velocity. Greater mass means greater inertia." },
  { text: "A body is in equilibrium when:", type:"mcq", marks:1,
    options:[{id:"a",text:"It is moving at constant speed"},{id:"b",text:"The net force acting on it is zero"},{id:"c",text:"All forces on it are equal"},{id:"d",text:"It has maximum velocity"}],
    correctAnswer:"b", explanation:"Equilibrium means the net force (and net torque for rotational equilibrium) is zero, so there is no acceleration." },
  { text: "The relationship between mass (m), force (F), and acceleration (a) is:", type:"mcq", marks:1,
    options:[{id:"a",text:"F = m/a"},{id:"b",text:"F = ma"},{id:"c",text:"a = Fm"},{id:"d",text:"m = Fa"}],
    correctAnswer:"b", explanation:"Newton's Second Law: F = ma. Force equals mass multiplied by acceleration." },
  { text: "Density is defined as:", type:"mcq", marks:1,
    options:[{id:"a",text:"Mass × volume"},{id:"b",text:"Volume / mass"},{id:"c",text:"Mass / volume"},{id:"d",text:"Weight / area"}],
    correctAnswer:"c", explanation:"Density = Mass / Volume. SI unit is kg/m³. It tells how much mass is packed into a unit volume." },
  { text: "The upward force exerted on an object submerged in a fluid is called:", type:"mcq", marks:1,
    options:[{id:"a",text:"Tension"},{id:"b",text:"Friction"},{id:"c",text:"Upthrust (buoyancy)"},{id:"d",text:"Normal reaction"}],
    correctAnswer:"c", explanation:"Upthrust (Archimedes' principle): the upward force equals the weight of fluid displaced by the submerged object." },
  { text: "Which type of energy does a stretched spring possess?", type:"mcq", marks:1,
    options:[{id:"a",text:"Kinetic energy"},{id:"b",text:"Thermal energy"},{id:"c",text:"Elastic potential energy"},{id:"d",text:"Chemical energy"}],
    correctAnswer:"c", explanation:"A stretched or compressed spring stores elastic potential energy. When released, it converts to kinetic energy." },
  { text: "The moment of a force about a pivot is calculated as:", type:"mcq", marks:1,
    options:[{id:"a",text:"Force × mass"},{id:"b",text:"Force × perpendicular distance from pivot"},{id:"c",text:"Force / distance"},{id:"d",text:"Mass × distance"}],
    correctAnswer:"b", explanation:"Moment (torque) = Force × perpendicular distance from the pivot. Unit: Newton-metre (N·m)." },
  { text: "Sound cannot travel through:", type:"mcq", marks:1,
    options:[{id:"a",text:"Solids"},{id:"b",text:"Liquids"},{id:"c",text:"Vacuum"},{id:"d",text:"Gases"}],
    correctAnswer:"c", explanation:"Sound is a mechanical wave that requires a medium to travel. In a vacuum, there are no particles to transmit vibrations." },
  { text: "A simple machine is used to:", type:"mcq", marks:1,
    options:[{id:"a",text:"Create energy"},{id:"b",text:"Multiply speed only"},{id:"c",text:"Transfer or transform force/displacement to make work easier"},{id:"d",text:"Destroy friction"}],
    correctAnswer:"c", explanation:"Simple machines (levers, pulleys, ramps) allow a smaller force over a larger distance to do the same work, or redirect forces." },
  { text: "The formula for kinetic energy is:", type:"mcq", marks:1,
    options:[{id:"a",text:"KE = mgh"},{id:"b",text:"KE = mv"},{id:"c",text:"KE = ½mv²"},{id:"d",text:"KE = Fd"}],
    correctAnswer:"c", explanation:"Kinetic energy KE = ½mv², where m is mass in kg and v is speed in m/s. Unit is Joules (J)." },
  { text: "The temperature at which all molecular motion theoretically ceases is:", type:"mcq", marks:1,
    options:[{id:"a",text:"0°C"},{id:"b",text:"-100°C"},{id:"c",text:"-273°C (absolute zero)"},{id:"d",text:"-100 K"}],
    correctAnswer:"c", explanation:"Absolute zero (0 K = −273.15°C) is the theoretical minimum temperature where particles have minimum kinetic energy." },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SS2 PHYSICS — 20 Questions (Waves, Electricity, Magnetism, Optics)
// ═══════════════════════════════════════════════════════════════════════════════
const ss2Physics = [
  { text: "The relationship between frequency (f), wavelength (λ), and wave speed (v) is:", type:"mcq", marks:1,
    options:[{id:"a",text:"v = f/λ"},{id:"b",text:"v = fλ"},{id:"c",text:"f = vλ"},{id:"d",text:"λ = vf"}],
    correctAnswer:"b", explanation:"The wave equation: v = fλ. Wave speed equals frequency multiplied by wavelength." },
  { text: "Which type of wave requires no medium for transmission?", type:"mcq", marks:1,
    options:[{id:"a",text:"Sound waves"},{id:"b",text:"Water waves"},{id:"c",text:"Electromagnetic waves"},{id:"d",text:"Seismic waves"}],
    correctAnswer:"c", explanation:"Electromagnetic waves (light, radio, X-rays) are self-propagating oscillating electric and magnetic fields that travel through vacuum." },
  { text: "Ohm's Law states that:", type:"mcq", marks:1,
    options:[{id:"a",text:"Current is inversely proportional to voltage"},{id:"b",text:"Voltage is directly proportional to current at constant resistance"},{id:"c",text:"Resistance decreases as temperature increases"},{id:"d",text:"Power equals current squared times voltage"}],
    correctAnswer:"b", explanation:"Ohm's Law: V = IR. At constant temperature (and thus constant resistance), voltage is directly proportional to current." },
  { text: "Resistors in series have:", type:"mcq", marks:1,
    options:[{id:"a",text:"The same voltage across each"},{id:"b",text:"The same current through each"},{id:"c",text:"Total resistance less than the smallest individual resistance"},{id:"d",text:"Independent currents"}],
    correctAnswer:"b", explanation:"In series circuits, the same current flows through all components. Total resistance = sum of individual resistances." },
  { text: "The unit of electrical resistance is the:", type:"mcq", marks:1,
    options:[{id:"a",text:"Volt"},{id:"b",text:"Ampere"},{id:"c",text:"Ohm"},{id:"d",text:"Watt"}],
    correctAnswer:"c", explanation:"The Ohm (Ω) is the SI unit of electrical resistance, named after Georg Simon Ohm." },
  { text: "Total internal reflection occurs when light travels from:", type:"mcq", marks:1,
    options:[{id:"a",text:"A less dense medium to a denser medium at any angle"},{id:"b",text:"A denser medium to a less dense medium at angles beyond the critical angle"},{id:"c",text:"Air into glass"},{id:"d",text:"Any medium at 90°"}],
    correctAnswer:"b", explanation:"Total internal reflection occurs when light in a denser medium hits the boundary at an angle greater than the critical angle." },
  { text: "The focal length of a convex lens is:", type:"mcq", marks:1,
    options:[{id:"a",text:"Always negative"},{id:"b",text:"The distance from the lens to where parallel rays converge"},{id:"c",text:"Equal to the radius of curvature"},{id:"d",text:"Independent of the lens material"}],
    correctAnswer:"b", explanation:"For a convex (converging) lens, the focal length is the distance from the optical centre to the principal focus where parallel rays meet." },
  { text: "Magnetic field lines around a straight current-carrying conductor are:", type:"mcq", marks:1,
    options:[{id:"a",text:"Straight lines parallel to the wire"},{id:"b",text:"Concentric circles centred on the wire"},{id:"c",text:"Radial lines pointing outward"},{id:"d",text:"Parallel lines perpendicular to the wire"}],
    correctAnswer:"b", explanation:"Using the right-hand grip rule, magnetic field lines form concentric circles around a straight current-carrying wire." },
  { text: "Electromagnetic induction occurs when:", type:"mcq", marks:1,
    options:[{id:"a",text:"A static magnetic field is placed near a conductor"},{id:"b",text:"A conductor is placed in a changing magnetic flux"},{id:"c",text:"Current flows through a solenoid"},{id:"d",text:"Two magnets are placed together"}],
    correctAnswer:"b", explanation:"Faraday's Law: an EMF is induced in a conductor whenever there is a change in the magnetic flux linking it." },
  { text: "The speed of light in a vacuum is approximately:", type:"mcq", marks:1,
    options:[{id:"a",text:"3 × 10⁶ m/s"},{id:"b",text:"3 × 10⁸ m/s"},{id:"c",text:"3 × 10¹⁰ m/s"},{id:"d",text:"3 × 10⁴ m/s"}],
    correctAnswer:"b", explanation:"c ≈ 3 × 10⁸ m/s (exactly 299,792,458 m/s). All electromagnetic waves travel at this speed in vacuum." },
  { text: "The refractive index of a medium is defined as:", type:"mcq", marks:1,
    options:[{id:"a",text:"Speed in medium / speed in vacuum"},{id:"b",text:"Speed in vacuum / speed in medium"},{id:"c",text:"Angle of incidence / angle of refraction"},{id:"d",text:"Wavelength in medium / wavelength in vacuum"}],
    correctAnswer:"b", explanation:"Refractive index n = c/v = speed of light in vacuum ÷ speed of light in medium. n is always ≥ 1." },
  { text: "Which of these is a longitudinal wave?", type:"mcq", marks:1,
    options:[{id:"a",text:"Light"},{id:"b",text:"Water ripples"},{id:"c",text:"Sound"},{id:"d",text:"Microwaves"}],
    correctAnswer:"c", explanation:"Sound is a longitudinal wave — particles vibrate parallel to the direction of wave propagation (compressions and rarefactions)." },
  { text: "Power dissipated in an electrical circuit is given by:", type:"mcq", marks:1,
    options:[{id:"a",text:"P = V/I"},{id:"b",text:"P = VI"},{id:"c",text:"P = V + I"},{id:"d",text:"P = R/I"}],
    correctAnswer:"b", explanation:"Electrical power P = VI = I²R = V²/R. SI unit is Watts (W) where 1 W = 1 J/s." },
  { text: "The direction of an induced current in electromagnetic induction is given by:", type:"mcq", marks:1,
    options:[{id:"a",text:"Ohm's Law"},{id:"b",text:"Fleming's Right-Hand Rule (Lenz's Law)"},{id:"c",text:"Newton's Third Law"},{id:"d",text:"Hooke's Law"}],
    correctAnswer:"b", explanation:"Lenz's Law (Fleming's right-hand rule for generators) states that the induced current opposes the change causing it." },
  { text: "Diffraction of light is most noticeable when:", type:"mcq", marks:1,
    options:[{id:"a",text:"The slit width is much larger than the wavelength"},{id:"b",text:"The slit width is comparable to or smaller than the wavelength"},{id:"c",text:"Light travels at high speed"},{id:"d",text:"The intensity of light is high"}],
    correctAnswer:"b", explanation:"Diffraction (bending around obstacles) is significant when the aperture or obstacle size is similar to the wavelength of the wave." },
  { text: "A transformer works by the principle of:", type:"mcq", marks:1,
    options:[{id:"a",text:"Self-induction"},{id:"b",text:"Mutual induction"},{id:"c",text:"Photoelectric effect"},{id:"d",text:"Thermionic emission"}],
    correctAnswer:"b", explanation:"A transformer uses mutual induction — changing current in the primary coil induces an EMF in the secondary coil through shared magnetic flux." },
  { text: "The photoelectric effect proves that light:", type:"mcq", marks:1,
    options:[{id:"a",text:"Travels as a continuous wave"},{id:"b",text:"Has only wave properties"},{id:"c",text:"Comes in discrete packets (photons) with energy E = hf"},{id:"d",text:"Cannot transfer energy to electrons"}],
    correctAnswer:"c", explanation:"Einstein explained the photoelectric effect by showing light consists of photons with energy E = hf, demonstrating wave-particle duality." },
  { text: "In a step-up transformer, the secondary coil has:", type:"mcq", marks:1,
    options:[{id:"a",text:"Fewer turns than the primary"},{id:"b",text:"The same number of turns as the primary"},{id:"c",text:"More turns than the primary"},{id:"d",text:"No coils"}],
    correctAnswer:"c", explanation:"A step-up transformer increases voltage: Vs/Vp = Ns/Np. More turns in secondary → higher output voltage." },
  { text: "Which colour of light has the highest frequency?", type:"mcq", marks:1,
    options:[{id:"a",text:"Red"},{id:"b",text:"Yellow"},{id:"c",text:"Green"},{id:"d",text:"Violet"}],
    correctAnswer:"d", explanation:"In the visible spectrum, violet light has the shortest wavelength and highest frequency. Red has the longest wavelength and lowest frequency." },
  { text: "The critical angle for a medium is the angle of incidence at which the angle of refraction is:", type:"mcq", marks:1,
    options:[{id:"a",text:"0°"},{id:"b",text:"45°"},{id:"c",text:"90°"},{id:"d",text:"180°"}],
    correctAnswer:"c", explanation:"At the critical angle, refracted light travels along the interface (90° to the normal). Beyond this angle, total internal reflection occurs." },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SS3 PHYSICS — 20 Questions (Modern Physics, Thermodynamics, Atomic, WAEC-level)
// ═══════════════════════════════════════════════════════════════════════════════
const ss3Physics = [
  { text: "According to Einstein's mass-energy equivalence, E = mc² means:", type:"mcq", marks:1,
    options:[{id:"a",text:"Energy and momentum are equal"},{id:"b",text:"A small mass is equivalent to an enormous amount of energy"},{id:"c",text:"Light has mass"},{id:"d",text:"Energy is always conserved in nuclear reactions only"}],
    correctAnswer:"b", explanation:"E = mc²: mass and energy are equivalent. Even a tiny mass (m) multiplied by c² (≈ 9×10¹⁶) yields enormous energy — the basis of nuclear power." },
  { text: "The half-life of a radioactive substance is:", type:"mcq", marks:1,
    options:[{id:"a",text:"The time for all atoms to decay"},{id:"b",text:"The time for half the atoms to decay"},{id:"c",text:"Half the radioactive emission rate"},{id:"d",text:"The time to reach maximum activity"}],
    correctAnswer:"b", explanation:"Half-life (t½) is the time for exactly half of the radioactive nuclei in a sample to undergo decay." },
  { text: "Which nuclear radiation has the greatest penetrating power?", type:"mcq", marks:1,
    options:[{id:"a",text:"Alpha (α)"},{id:"b",text:"Beta (β)"},{id:"c",text:"Gamma (γ)"},{id:"d",text:"Alpha and beta equally"}],
    correctAnswer:"c", explanation:"Gamma radiation (γ) is high-energy electromagnetic radiation that can penetrate several centimetres of lead. Alpha is stopped by paper; beta by a few mm of aluminium." },
  { text: "Bohr's model of the atom introduced the concept that electrons:", type:"mcq", marks:1,
    options:[{id:"a",text:"Are distributed throughout the nucleus"},{id:"b",text:"Orbit the nucleus in fixed energy levels (shells)"},{id:"c",text:"Have no definite position"},{id:"d",text:"Continuously emit radiation"}],
    correctAnswer:"b", explanation:"Bohr proposed that electrons occupy discrete, quantised energy levels. Energy is emitted or absorbed only when electrons jump between levels." },
  { text: "The first law of thermodynamics states:", type:"mcq", marks:1,
    options:[{id:"a",text:"Heat flows from cold to hot"},{id:"b",text:"Entropy always increases"},{id:"c",text:"The internal energy change equals heat added minus work done by the system"},{id:"d",text:"Energy can be created at absolute zero"}],
    correctAnswer:"c", explanation:"First Law (conservation of energy for thermodynamics): ΔU = Q – W, where Q is heat supplied and W is work done by the system." },
  { text: "In nuclear fission:", type:"mcq", marks:1,
    options:[{id:"a",text:"Two light nuclei combine to form a heavier one"},{id:"b",text:"A heavy nucleus splits into smaller fragments releasing energy"},{id:"c",text:"A nucleus emits a beta particle"},{id:"d",text:"A proton is converted to a neutron"}],
    correctAnswer:"b", explanation:"Fission: a heavy nucleus (e.g. U-235) absorbs a neutron, becomes unstable, and splits into smaller nuclei plus 2-3 neutrons and energy." },
  { text: "The de Broglie wavelength of a particle is given by:", type:"mcq", marks:1,
    options:[{id:"a",text:"λ = h/mv"},{id:"b",text:"λ = mv/h"},{id:"c",text:"λ = hv/m"},{id:"d",text:"λ = m/hv"}],
    correctAnswer:"a", explanation:"de Broglie: λ = h/p = h/(mv), where h is Planck's constant. This shows every moving particle has a wave nature." },
  { text: "A semiconductor has electrical conductivity:", type:"mcq", marks:1,
    options:[{id:"a",text:"Always higher than metals"},{id:"b",text:"Between that of conductors and insulators"},{id:"c",text:"Always zero"},{id:"d",text:"Equal to insulators"}],
    correctAnswer:"b", explanation:"Semiconductors (Si, Ge) have conductivity between metals and insulators, and their conductivity increases with temperature." },
  { text: "Entropy in thermodynamics is a measure of:", type:"mcq", marks:1,
    options:[{id:"a",text:"Heat content of a system"},{id:"b",text:"Degree of disorder or randomness in a system"},{id:"c",text:"The work done by the system"},{id:"d",text:"Internal energy"}],
    correctAnswer:"b", explanation:"Entropy (S) measures disorder. The second law states entropy of an isolated system tends to increase (natural processes are irreversible)." },
  { text: "X-rays are produced when:", type:"mcq", marks:1,
    options:[{id:"a",text:"Electrons collide with a metal target"},{id:"b",text:"Protons decay in the nucleus"},{id:"c",text:"Gamma rays pass through matter"},{id:"d",text:"Neutrons bombard uranium"}],
    correctAnswer:"a", explanation:"X-rays are generated in an X-ray tube when high-speed electrons are suddenly decelerated upon striking a tungsten anode target." },
  { text: "The Heisenberg Uncertainty Principle states that:", type:"mcq", marks:1,
    options:[{id:"a",text:"Energy is always conserved"},{id:"b",text:"It is impossible to know both the exact position and momentum of a particle simultaneously"},{id:"c",text:"Electrons have wave-like properties"},{id:"d",text:"The speed of light is constant"}],
    correctAnswer:"b", explanation:"Heisenberg: Δx·Δp ≥ h/4π. The more precisely we know a particle's position, the less precisely we can know its momentum, and vice versa." },
  { text: "Nuclear fusion requires:", type:"mcq", marks:1,
    options:[{id:"a",text:"Heavy elements like uranium"},{id:"b",text:"Extreme temperatures and pressures to overcome nuclear repulsion"},{id:"c",text:"A chain reaction of neutrons"},{id:"d",text:"A moderator to slow neutrons"}],
    correctAnswer:"b", explanation:"Fusion (e.g. in stars) requires temperatures of ~10⁷ K and high pressure to force hydrogen nuclei close enough for the strong nuclear force to bind them." },
  { text: "A p-n junction diode allows current to flow:", type:"mcq", marks:1,
    options:[{id:"a",text:"In both directions equally"},{id:"b",text:"Only in reverse bias"},{id:"c",text:"Only in forward bias"},{id:"d",text:"In neither direction"}],
    correctAnswer:"c", explanation:"A diode conducts in forward bias (p-side positive) and blocks in reverse bias, acting as a one-way valve for current." },
  { text: "The Doppler effect in sound causes:", type:"mcq", marks:1,
    options:[{id:"a",text:"A change in the amplitude of sound"},{id:"b",text:"An apparent change in frequency due to relative motion between source and observer"},{id:"c",text:"Sound waves to travel faster"},{id:"d",text:"Sound to travel through vacuum"}],
    correctAnswer:"b", explanation:"The Doppler effect: a moving source or observer changes the observed frequency — higher pitch when approaching, lower when receding." },
  { text: "Which phenomenon demonstrates the particle nature of light?", type:"mcq", marks:1,
    options:[{id:"a",text:"Diffraction"},{id:"b",text:"Interference"},{id:"c",text:"Photoelectric effect"},{id:"d",text:"Polarisation"}],
    correctAnswer:"c", explanation:"The photoelectric effect shows light behaves as particles (photons). Diffraction, interference, and polarisation demonstrate wave nature." },
  { text: "The charge of an electron is approximately:", type:"mcq", marks:1,
    options:[{id:"a",text:"+1.6 × 10⁻¹⁹ C"},{id:"b",text:"-1.6 × 10⁻¹⁹ C"},{id:"c",text:"-9.1 × 10⁻³¹ C"},{id:"d",text:"+9.1 × 10⁻³¹ C"}],
    correctAnswer:"b", explanation:"The electron has a charge of −1.6 × 10⁻¹⁹ coulombs. The 9.1 × 10⁻³¹ figure is the electron's mass in kilograms, not its charge." },
  { text: "The efficiency of a heat engine is calculated as:", type:"mcq", marks:1,
    options:[{id:"a",text:"Work output / heat input × 100%"},{id:"b",text:"Heat input / work output × 100%"},{id:"c",text:"Work output × heat input"},{id:"d",text:"Heat output / heat input × 100%"}],
    correctAnswer:"a", explanation:"Efficiency = (Useful work output / Total heat input) × 100%. No engine is 100% efficient due to entropy." },
  { text: "Pair production occurs when a gamma photon:", type:"mcq", marks:1,
    options:[{id:"a",text:"Collides with an electron"},{id:"b",text:"Passes near a heavy nucleus and creates an electron-positron pair"},{id:"c",text:"Is absorbed by a proton"},{id:"d",text:"Interacts with a neutron"}],
    correctAnswer:"b", explanation:"Pair production: a γ photon with energy ≥ 1.022 MeV is converted into an electron (e⁻) and positron (e⁺) near a nucleus." },
  { text: "In simple harmonic motion (SHM), the restoring force is:", type:"mcq", marks:1,
    options:[{id:"a",text:"Constant in magnitude and direction"},{id:"b",text:"Proportional to and directed towards the equilibrium position"},{id:"c",text:"Proportional to velocity"},{id:"d",text:"Always perpendicular to displacement"}],
    correctAnswer:"b", explanation:"SHM: F = –kx. The restoring force is proportional to displacement and always directed toward the equilibrium position." },
  { text: "The binding energy of a nucleus represents:", type:"mcq", marks:1,
    options:[{id:"a",text:"The energy needed to add more neutrons"},{id:"b",text:"The energy released when electrons orbit the nucleus"},{id:"c",text:"The energy required to completely separate the nucleus into its constituent nucleons"},{id:"d",text:"The kinetic energy of the nucleus"}],
    correctAnswer:"c", explanation:"Nuclear binding energy is the energy equivalent of the mass defect — the energy needed to break the nucleus into its individual protons and neutrons." },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SEED FUNCTION
// ═══════════════════════════════════════════════════════════════════════════════
async function seed() {
  await mongoose.connect(MONGODB_URL);
  console.log("✅  Connected to MongoDB");

  const admin = await User.findOne({ role: "admin" });
  if (!admin) {
    console.error("❌  No admin user found. Run seedAdmin.js first.");
    process.exit(1);
  }
  console.log(`👤  Using admin: ${admin.name} (${admin._id})`);

  const examsToCreate = [
    // ── SS1 ────────────────────────────────────────────────
    {
      title: "Biology — SS1 Core Concepts",
      description: "Covers cell biology, nutrition, respiration, enzymes, and reproduction. 20 MCQ questions.",
      subject: "Biology", className: "SS1", type: "mcq",
      duration: 30, passMark: 50, status: "draft",
      allowReview: true, shuffleQ: false, shuffleOpts: false, attemptsAllowed: 1,
      questions: ss1Biology,
    },
    {
      title: "Chemistry — SS1 Core Concepts",
      description: "Covers atomic structure, bonding, states of matter, and basic reactions. 20 MCQ questions.",
      subject: "Chemistry", className: "SS1", type: "mcq",
      duration: 30, passMark: 50, status: "draft",
      allowReview: true, shuffleQ: false, shuffleOpts: false, attemptsAllowed: 1,
      questions: ss1Chemistry,
    },
    {
      title: "Physics — SS1 Core Concepts",
      description: "Covers measurements, motion, forces, energy, and pressure. 20 MCQ questions.",
      subject: "Physics", className: "SS1", type: "mcq",
      duration: 30, passMark: 50, status: "draft",
      allowReview: true, shuffleQ: false, shuffleOpts: false, attemptsAllowed: 1,
      questions: ss1Physics,
    },
    // ── SS2 ────────────────────────────────────────────────
    {
      title: "Biology — SS2 Core Concepts",
      description: "Covers genetics, ecology, evolution, physiology, and behaviour. 20 MCQ questions.",
      subject: "Biology", className: "SS2", type: "mcq",
      duration: 30, passMark: 50, status: "draft",
      allowReview: true, shuffleQ: false, shuffleOpts: false, attemptsAllowed: 1,
      questions: ss2Biology,
    },
    {
      title: "Chemistry — SS2 Core Concepts",
      description: "Covers stoichiometry, acids/bases, kinetics, and introductory organic chemistry. 20 MCQ questions.",
      subject: "Chemistry", className: "SS2", type: "mcq",
      duration: 30, passMark: 50, status: "draft",
      allowReview: true, shuffleQ: false, shuffleOpts: false, attemptsAllowed: 1,
      questions: ss2Chemistry,
    },
    {
      title: "Physics — SS2 Core Concepts",
      description: "Covers waves, optics, electricity, and magnetism. 20 MCQ questions.",
      subject: "Physics", className: "SS2", type: "mcq",
      duration: 30, passMark: 50, status: "draft",
      allowReview: true, shuffleQ: false, shuffleOpts: false, attemptsAllowed: 1,
      questions: ss2Physics,
    },
    // ── SS3 ────────────────────────────────────────────────
    {
      title: "Biology — SS3 Advanced (WAEC Prep)",
      description: "Covers genetics, biotechnology, ecology, evolution, and physiology at WAEC level. 20 MCQ questions.",
      subject: "Biology", className: "SS3", type: "mcq",
      duration: 30, passMark: 50, status: "draft",
      allowReview: true, shuffleQ: false, shuffleOpts: false, attemptsAllowed: 1,
      questions: ss3Biology,
    },
    {
      title: "Chemistry — SS3 Advanced (WAEC Prep)",
      description: "Covers organic chemistry, electrochemistry, equilibrium, and industrial chemistry. 20 MCQ questions.",
      subject: "Chemistry", className: "SS3", type: "mcq",
      duration: 30, passMark: 50, status: "draft",
      allowReview: true, shuffleQ: false, shuffleOpts: false, attemptsAllowed: 1,
      questions: ss3Chemistry,
    },
    {
      title: "Physics — SS3 Advanced (WAEC Prep)",
      description: "Covers modern physics, thermodynamics, nuclear physics, and electronics. 20 MCQ questions.",
      subject: "Physics", className: "SS3", type: "mcq",
      duration: 30, passMark: 50, status: "draft",
      allowReview: true, shuffleQ: false, shuffleOpts: false, attemptsAllowed: 1,
      questions: ss3Physics,
    },
  ];

  let created = 0;
  for (const examData of examsToCreate) {
    const exists = await Exam.findOne({ title: examData.title });
    if (exists) {
      console.log(`⏭️   Already exists: "${examData.title}" — skipping`);
      continue;
    }
    const exam = await Exam.create({
      ...examData,
      createdBy: admin._id,
      creatorName: admin.name,
    });
    console.log(`✅  Created: "${exam.title}" (${exam.questions.length} questions, ${exam.totalMarks} marks)`);
    created++;
  }

  console.log(`\n🎉  Done. ${created} exam(s) created. Activate them from the Admin Dashboard.`);
  await mongoose.disconnect();
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
